name: Auto Generate File

on:
  schedule:
    - cron: "*/10 * * * *"   # tiap 5 menit (buat demo)
  workflow_dispatch:        # tombol manual (opsional)

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Buat file otomatis
        run: |
          echo "Laporan otomatis CI/CD" > laporan.txt
          echo "Dibuat pada: $(date)" >> laporan.txt

      - name: Commit ke repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add laporan.txt
          git commit -m "Auto update laporan.txt"
          git push
